### ISSUE TITLE
infeasibility pour MakeDesign avec le topo TP2

### ISSUE THREAD

**Issue by lolow** [lolow/neatwork#2]
Les deux premieres fichiers joints concernent TP2. Le design est obtenu en prenant une fraction de robinets ouverts égale à 0.6 et une qualité de service égale à 0.65. Donc ça marche. 
Ma première idée est qu'il y a un bogue dans ta version. Il y a toujours une solution réalisable pour ce problème : elle consistere à ne prendre qu'un type de tuyau, celui avec le plus gros diamètre. Je suggère que tu regardes comment le pré-processeur utilise la base de données sur les diamètres disponibles. Tu peux essayer l'expérience en n'utilisant que le tuyau avec le plus grand diamètre.
Je fais l'expérience de mon côté, et patatras les ennuis commencent : problème non réalisable ! Si je prends comme tuyau disponible le 8 pouces sdr 17 et diam = 0.193 (et tous les orifices) ça ne me donne pas de solution. Si j'ajoute le 1/2" sdr 40 et diam = 0.0158, NeatWork trouve une solution (voir fichier joint).

L'erreur est bien présente dans l'ancienne version de NeatWork, quoique d'une façon un peu différente. Dans l'article, j'ai formulé le problème du design avec comme contraintes principales que la perte de charge totale sur chaque chemin conduisant à un robinet (incluant la perte de charge au robinet) soit inférieure ou égale à la différence d'altitude. Remplacer des tuyaux plus petits par des plus gros diminue la friction et ne fait que renforcer la réalisabilité des contraintes. D'où l'absurdité des résultats obtenus avec le vieux NeatWork.

[TP2.zip](https://github.com/lolow/neatwork/files/682030/TP2.zip)

**Comment by jphvial** [comment]
Je viens de refaire les expériences avec TP2. Je ne reproduis pas le phénomène que j'avais observé, ce qui veux dire probablement que je suis miro. Ma remarque doit donc être rangée aux oubliettes. Il faut dire qu'il y a bp de TP2. C'est un projet de 2007 sous le nom de La Enea. J'ai une version plus récente résultant d'une réhabilitation. Peut-être est-ce la source de la confusion.
