### ISSUE TITLE
Identifier la structure de F et y pour la simulation

### ISSUE THREAD

**Issue by lolow** [lolow/neatwork#5]

**Comment by lolow** [comment]
A partir de l'exemple et du code, on peut deduire la structure des 2 vecteurs:
![image](https://github.com/lolow/neatwork/assets/28093/a5700183-23ec-4f2b-b921-81b5b83f0e42)

On voit que l’arbre à été étendu en P3 et P2 pour chaque robinet. Le réseau est stocké de la facon suivante:

nvector/nsubvector (3eme ligne est group_index_tap):

<table>
  <tr>
   <td>0
   </td>
   <td>1
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>4
   </td>
   <td>5
   </td>
   <td>6
   </td>
   <td>7
   </td>
   <td>8
   </td>
   <td>9
   </td>
   <td>10
   </td>
   <td>11
   </td>
   <td>12
   </td>
   <td>13
   </td>
  </tr>
  <tr>
   <td>Source
   </td>
   <td>Source*A
   </td>
   <td>A
   </td>
   <td>B
   </td>
   <td>C
   </td>
   <td>P2
   </td>
   <td>P3
   </td>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
  <tr>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>2
   </td>
   <td>2
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>3
   </td>
   <td>0
   </td>
  </tr>
</table>


pvector/psubvector (3eme ligne est group_index_tap):

<table>
  <tr>
   <td>0
   </td>
   <td>1
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>4
   </td>
   <td>5
   </td>
   <td>6
   </td>
   <td>7
   </td>
   <td>8
   </td>
   <td>9
   </td>
   <td>10
   </td>
   <td>11
   </td>
   <td>12
   </td>
  </tr>
  <tr>
   <td>Source
   </td>
   <td>Source*A
   </td>
   <td>A
   </td>
   <td>A
   </td>
   <td>B
   </td>
   <td>C
   </td>
   <td>B
   </td>
   <td>P2
   </td>
   <td>P2
   </td>
   <td>P2
   </td>
   <td>P3
   </td>
   <td>P3
   </td>
   <td>C
   </td>
  </tr>
  <tr>
   <td>Source*A
   </td>
   <td>A
   </td>
   <td>B
   </td>
   <td>C
   </td>
   <td>P2
   </td>
   <td>P3
   </td>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
  <tr>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>0
   </td>
   <td>2
   </td>
   <td>2
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>3
   </td>
   <td>0
   </td>
  </tr>
</table>


tvector/tsubvector


<table>
  <tr>
   <td>0
   </td>
   <td>1
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>4
   </td>
   <td>5
   </td>
   <td>6
   </td>
  </tr>
  <tr>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
</table>

### Stockage des résultats des simulations dans `RunSimulation.TapsStatistic`

**Flots aux tuyaux (lines 503-553):**

* Loop over all psubvectors, dans l’ordre, si groupe de robinets, aller directement au dernier
    * on obtient `pipe`
    * attribuer 

**Pression aux robinets (lines 481-501):**

* Loop over all nsubvectors, dans l’ordre, si groupe de robinets, aller directement au dernier
    * on obtient `node`
    * affecter la pression au noeud base sur y[i], i = index noeud.
    * Si c’est un robinet, on obtient `tap` corresponds
        * ajuster la pression au `node` en utilisant:
            * F[psubvector.size() + 1 + index_tap], index_tap = index noeud
            * parametres du`node` et du `tap`

Dans l’algo et donc F[psubvector.size() + 1 + i], l’ordre des taps est celui de tsubvector:

<table>
  <tr>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
</table>

### Structure de y et F

**Contenu de y**

Pressions aux noeuds dans l’ordre de nsubvectors

**Contenu de F**

```
Part1: F[0]...F[psubvector.size()]
``` 

<table>
  <tr>
   <td>
0
   </td>
   <td>1
   </td>
   <td>2
   </td>
   <td>3
   </td>
   <td>4
   </td>
   <td>5
   </td>
   <td>6
   </td>
   <td>7
   </td>
   <td>8
   </td>
   <td>9
   </td>
   <td>10
   </td>
   <td>11
   </td>
   <td>12
   </td>
  </tr>
  <tr>
   <td>Source
   </td>
   <td>Source*A
   </td>
   <td>A
   </td>
   <td>A
   </td>
   <td>B
   </td>
   <td>C
   </td>
   <td>B
   </td>
   <td>P2
   </td>
   <td>P2
   </td>
   <td>P2
   </td>
   <td>P3
   </td>
   <td>P3
   </td>
   <td>C
   </td>
  </tr>
  <tr>
   <td>Source*A
   </td>
   <td>A
   </td>
   <td>B
   </td>
   <td>C
   </td>
   <td>P2
   </td>
   <td>P3
   </td>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
</table>

```
Part2: F[psubvector.size() + 1 ]...F[psubvector.size() + tsubvector.size()]
```

<table>
  <tr>
   <td>
13
   </td>
   <td>14
   </td>
   <td>15
   </td>
   <td>16
   </td>
   <td>17
   </td>
   <td>18
   </td>
   <td>19
   </td>
  </tr>
  <tr>
   <td>P1
   </td>
   <td>P2_a
   </td>
   <td>P2_b
   </td>
   <td>P2_c
   </td>
   <td>P3_a
   </td>
   <td>P3_b
   </td>
   <td>P4
   </td>
  </tr>
</table>

```
Part3: F[psubvector.size() + tsubvector.size]...F[33]
```
= 0

**Comment by jphvial** [comment]
Nous avons inclus le cas de robinets multiples dès la création de NeatWork. Le traitement informatique a été fait de la manière la plus immédiate en la connexion d'un robinet à la prise multiple comme un arc du réseau. C'est une approche évidente mais pas adapté. La bonne approche est plus simple, mais le plus simple encore serait de supprimer l'option des robinets multiples dans le mise à jour du moment. 
La question que je me pose est de savoir si le prétraitement d'une simulation introduit un arc fictif du robinet au terminal lorsqu'il n'y a qu'un seul robinet connecté au robinet. Mon code de simulation ne le fait pas, mais l'information est disponible puisque le débit dans cet arc fictif est le même que dans l'arc qui aboutit au nœud terminal.

**Comment by jphvial** [comment]
[Conseils pour NeatWork.pdf](https://github.com/user-attachments/files/15520779/Conseils.pour.NeatWork.pdf)
Contient des infos concernant le traitement à venir des robinets multiples et d'autres éléments.
